添加 docker-compose 部署的配置和文档
lilydjwg/luoxu pull request #6
Opened 2023-07-13 16:34 UTC by zhpjy

2023-07-14 06:27 UTC, lilydjwg requested changes
目前这些变更不够通用，并会增加大量维护成本。

2023-07-14 06:27 UTC, lilydjwg commented on Dockerfile
> +FROM ubuntu:22.04 AS builder-image
为什么要用 Ubuntu？为什么要硬编码版本？

2023-07-14 06:27 UTC, lilydjwg commented on Dockerfile
> +RUN sed -i 's@//.*archive.ubuntu.com@//mirrors.ustc.edu.cn@g' /etc/apt/sources.list &&\
为什么要用中国大陆的镜像？不应该是选一个离服务器近的吗？

2023-07-14 06:27 UTC, lilydjwg commented on Dockerfile
> +    RUST_VERSION=1.70.0\
请使用近期版本，而不是硬编码某个肯定会成为历史的版本。

2023-07-14 06:27 UTC, lilydjwg commented on Dockerfile
> +    apt-get update && apt-get install -y python3.11 pip libpython3.11-dev opencc &&\
不要硬编码 Python 版本。

2023-07-14 06:27 UTC, lilydjwg commented on deploy/docker-compose.yml
> +  luoxu-back:
落絮的背？

2023-07-14 06:27 UTC, lilydjwg commented on deploy/docker-compose.yml
> +      POSTGRES_USER: PGroonga
既然这里硬编码了特定版本的数据库，那么需要进行大版本更新如何进行呢？

2023-07-14 06:27 UTC, lilydjwg commented on querytrans/rust-toolchain.toml
> +channel = "nightly-2023-06-27"
为什么要 pin 到某个 nightly 版本？

2023-07-14 06:27 UTC, lilydjwg commented on requirements.txt
> +PySocks
这项依赖通常是不必要的。

2023-07-19 15:27 UTC, zhpjy commented on deploy/docker-compose.yml
> +      POSTGRES_USER: PGroonga
大版本更新建议备份数据库数据文件夹 db，然后修改 docker-compose.yml 中的版本号，按照官方的升级说明文档进行升级。

2023-07-19 15:51 UTC, zhpjy commented on querytrans/rust-toolchain.toml
> +channel = "nightly-2023-06-27"
由于这个 https://github.com/rust-lang/rust/issues/113152，编译时会报和这个 issue 一样的错误。

2023-07-19 15:58 UTC, lilydjwg commented on querytrans/rust-toolchain.toml
> +channel = "nightly-2023-06-27"
原来撞上 bug 了……那这么锁版本也不好，容易忘记更新（因为我自己不用）。

2023-07-19 15:59 UTC, lilydjwg commented on deploy/docker-compose.yml
> +      POSTGRES_USER: PGroonga
哪个「官方」？

2023-07-19 16:01 UTC, lilydjwg commented
我对 docker 这套东西不熟，也不想自己去测试它能不能用。这部分还是你单独维护比较好。

2023-07-19 16:03 UTC, zhpjy commented
ok 那我取消这个合并好啦。我可以基于这个维护一个 docker 的 image 吗？

2023-07-19 16:05 UTC, closed without merging

2023-07-19 16:19 UTC, lilydjwg commented
可以啊。注意让用户能够很清楚地了解到该 image 不是 luoxu 的作者制作的即可。